version: "3"

env:
  PYO3_PYTHON: '{{if eq OS "windows"}}{{.USER_WORKING_DIR}}\\.venv\\Scripts\\python.exe{{else}}.venv/bin/python{{end}}'

vars:
  QUIET: false

tasks:
  default:
    desc: Rebuild mixed workspaces and run all checks
    cmds:
      - task: generate-stubs
        vars:
          QUIET: true
      - task: sync-env
        vars:
          QUIET: true
      - task: rust-checks
        vars:
          QUIET: true
      - task: python-checks
        vars:
          QUIET: true

  generate-stubs:
    desc: Generate stubs for mixed workspaces
    dir: mixed/algo
    sources:
      - src/**
      - Cargo.toml
    generates:
      - python/algo/**
    cmds:
      - cargo run --bin stub_gen {{if .QUIET}}--quiet{{end}}

  sync-env:
    desc: Sync Python environment using uv
    sources:
      - Cargo.toml
      - pyproject.toml
      - mixed/**
      - python/**
    cmds:
      - uv sync {{if .QUIET}}--quiet{{end}}

  rust-checks:
    desc: Run Rust checks
    sources:
      - Cargo.toml
      - mixed/**
    cmds:
      - cargo check {{if .QUIET}}--quiet{{end}}
      - cargo fmt --check {{if .QUIET}}--quiet{{end}}
      - cargo test {{if .QUIET}}--quiet{{end}}  # TODO: it will not quiet fully
      - cargo clippy {{if .QUIET}}--quiet{{end}} --all-targets --all-features -- -D warnings 

  python-checks:
    desc: Run Python type and lint checks
    sources:
      - pyproject.toml
      - mixed/**
      - python/**
    cmds:
      - uv run mypy .  # TODO: add quiet flag when supported
      - uv run ruff check --fix {{if .QUIET}}--quiet{{end}}
      - uv run pytest {{if .QUIET}}--quiet{{end}}  # TODO: it will not quiet fully

  python-reinstall:
    desc: Reinstall Python dependencies
    cmds:
      - uv sync --reinstall 
